name: Sayuri Daily Reminder 🌸

on:
  schedule:
    - cron: "0 3 * * *"  # Every day at 3 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  sayuri-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Sayuri
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py
